### ISSUE TITLE
pygame.error: mixer not initialized

### ISSUE THREAD

**Issue by iamharshit188** [tusharhero/darwinio#10]
Onto Running : 

```
pygame-ce 2.3.2 (SDL 2.26.5, Python 3.11.4)
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5181:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5181:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5181:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5704:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "/sec/home/iamharshit188/.local/pipx/.cache/e2de8fd435481cf/bin/darwinio", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/sec/home/iamharshit188/.local/pipx/.cache/e2de8fd435481cf/lib/python3.11/site-packages/darwinio/__main__.py", line 150, in cli
    main((1000, 750), 60, (50, 50))
  File "/sec/home/iamharshit188/.local/pipx/.cache/e2de8fd435481cf/lib/python3.11/site-packages/darwinio/__main__.py", line 53, in main
    pg.mixer.music.load(path)
pygame.error: mixer not initialized


```

Distribution : ArchLinux & Kali Linux

**Comment by tusharhero** [comment]
X11 right?

**Comment by tusharhero** [comment]
Please let me know if it works now.
